mysql:
  container_name: cyclops-mysql
  build: ./services/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    MYSQL_DATABASE: dev
    MYSQL_USER: dev
    MYSQL_PASSWORD: "${MYSQL_DEV_PASSWORD}"
  ports:
    - "${MYSQL_PORT}"
  volumes:
    - "${PWD}/services/mysql/data:/var/lib/mysql"
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
phpfpm:
  container_name: cyclops-phpfpm
  build: ./services/phpfpm
  privileged: true
  volumes:
    - "${PWD}/project:/var/www/project"
  links:
    - mysql:mysql
nginx:
  container_name: "${VIRTUAL_HOST}"
  build: ./services/nginx
  environment:
    VIRTUAL_HOST: "${VIRTUAL_HOST}"
  volumes:
    - "${PWD}/project:/var/www/project"
  links:
    - phpfpm:phpfpm
