version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.16.1

    steps:
      - checkout

      - run:
          command: |
            docker pull jwilder/nginx-proxy;
            docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy;

      - run:
          command: cp .env.example .env
